Add RELEASING documents for release process
abcxyz/abc-updater pull request #30
Opened 2024-03-18 23:46 UTC by pdewilde

Forgot to add in previous pr

2024-03-18 23:54 UTC, sethvargo requested changes
Could we switch to the new release process like in jvs instead? It handles the major/minor/patch.

2024-03-19 00:13 UTC, pdewilde commented
> Could we switch to the new release process like in jvs instead? It handles the major/minor/patch.

I'm having trouble finding any documentation for the new release process. There isn't a RELEASING.md in the `jvs` repo, and I've searched some internal documentation.

2024-03-19 17:42 UTC, drevell approved these changes

2024-03-19 22:56 UTC, pdewilde commented
Closing to re-create with new process

2024-03-19 22:56 UTC, closed without merging